- hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: install the locales package
    apt: pkg=locales state=present

  - name: ensure the en_US locale exists
    locale_gen: name=en_US.UTF-8 state=present

  - name: ensure the ro_RO locale exists
    locale_gen: name=ro_RO.UTF-8 state=present        

  - name: set the locale
    command: /usr/sbin/update-locale LANG=en_US.UTF-8 --reset    

  - name: Installing repo for Java 8 in Ubuntu
    become: true
    apt_repository: 
      repo: 'ppa:openjdk-r/ppa'
      state: present

  - name: ensure packages are installed
    apt: name={{ item }}
    with_items:
        - make
        - build-essential
        - python
        - python-dev
        - python-virtualenv
        - python3-pip
        - libevent-dev
        - libpq-dev
        - zlib1g-dev
        - python-pip
        - libjpeg-dev
        - software-properties-common
        - ruby
        - ruby-dev
        - postgresql-9.3
        - postgresql-common
        - libpq-dev
        - python-psycopg2
        - unzip
        - recode
        - git

  - name: ensure postgresql user is created
    become: true
    become_user: postgres
    postgresql_user: name=eray password=eray role_attr_flags=CREATEDB,SUPERUSER

  - name: ensure database is created
    become: true
    become_user: postgres
    postgresql_db: name=eray login_user=postgres encoding=UTF-8 lc_collate=en_US.UTF-8 lc_ctype=en_US.UTF-8

  - name: Install software-properties-common for apt-add-repository command
    sudo: yes
    action: apt pkg=software-properties-common state=installed
    tags: heroku

  - name: Add Heroku release key for package verification
    sudo: yes
    action: apt_key url=http://cli-assets.heroku.com/apt/release.key state=present
    tags: heroku

  - name: Add Heroku APT repository
    tags: heroku
    sudo: yes
    action: apt_repository repo="deb https://cli-assets.heroku.com/branches/stable/apt ./" state=present

  - name: Install Heroku toolbelt
    tags: heroku
    sudo: yes
    action: apt name=heroku state=latest update_cache=yes cache_valid_time=86400

- hosts: all
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.ruby
    - geerlingguy.nodejs
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - geerlingguy.solr

- hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
  - name: Copy Solr schema
    copy:
      src: ../../solr_schema.xml
      dest: /var/solr/collection1/conf/schema.xml

  - name: Copy Solr config
    copy:
      src: ../../solrconfig.xml
      dest: /var/solr/collection1/conf/solrconfig.xml

  - name: restart Solr
    service: name=solr state=restarted      
