# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eray', '0002_auto_20170714_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='vote_count',
        ),
    ]
