# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eray', '0008_auto_20170818_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ASK', 'ASK'), ('ANSWER', 'ANSWER'), ('COMMENT', 'COMMENT'), ('ACCEPTED', 'ACCEPTED'), ('WAS_ACCEPTED', 'WAS_ACCEPTED')], max_length=50)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eray.Answer')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eray.Comment')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eray.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
