# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eray', '0010_auto_20170822_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterUniqueTogether(
            name='useractionstream',
            unique_together=set([('user', 'question', 'answer', 'comment', 'action_type')]),
        ),
    ]
