# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eray', '0011_auto_20170828_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=140, null=True),
        ),
    ]
