# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eray', '0012_auto_20170828_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
