# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eray', '0014_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_instant', models.BooleanField(default=False)),
                ('notify_hourly', models.BooleanField(default=False)),
                ('notify_daily', models.BooleanField(default=True)),
                ('notify_weekly', models.BooleanField(default=False)),
                ('notify_comment', models.BooleanField(default=True)),
                ('notify_answer', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserNotification',
            new_name='UserNotificationStream',
        ),
    ]
