# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eray', '0015_auto_20170905_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eray.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscribedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eray.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usernotificationsetting',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_answer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_daily',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_hourly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_instant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationstream',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eray.Tag'),
        ),
        migrations.AlterField(
            model_name='usernotificationstream',
            name='notification_type',
            field=models.CharField(choices=[('NEW_ANSWER', 'NEW_ANSWER'), ('NEW_COMMENT', 'NEW_COMMENT'), ('ANSWER_ACCEPTED', 'ANSWER_ACCEPTED'), ('NEW_QUESTION', 'NEW_QUESTION')], max_length=50),
        ),
        migrations.DeleteModel(
            name='UserNotificationSetting',
        ),
    ]
