# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eray', '0016_auto_20170921_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractionstream',
            unique_together=set([]),
        ),
    ]
