# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eray', '0017_auto_20170921_1600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscribedquestion',
            unique_together=set([('user', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscribedtag',
            unique_together=set([('user', 'tag')]),
        ),
    ]
