# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eray', '0018_auto_20170922_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscribedquestion',
            old_name='question',
            new_name='subscribed_obj',
        ),
        migrations.RenameField(
            model_name='usersubscribedtag',
            old_name='tag',
            new_name='subscribed_obj',
        ),
        migrations.AlterUniqueTogether(
            name='usersubscribedquestion',
            unique_together=set([('user', 'subscribed_obj')]),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscribedtag',
            unique_together=set([('user', 'subscribed_obj')]),
        ),
    ]
