# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-05 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eray', '0019_auto_20170922_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
