# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eray', '0021_auto_20171024_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationstream',
            name='notification_status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
